import numpy as np
import time
array_1d=np.array([1,2,3,4,5])
array_2d=np.array([[1,2,3],[4,5,6]])
array_3d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("1D Array:\n",array_1d)
print("2D Array:\n",array_2d)
print("3D Array:\n",array_3d)
print("Addition:",array_1d+10)
print("Multiplication:",array_1d*2)
print("Square:",np.square(array_1d))
print("Square Root:",np.sqrt(array_1d))
matrix=np.array([[1,2,3],[4,5,6]])
print("Broadcasting Result:\n",matrix+np.array([10,20,30]))
print("Mean:",np.mean(array_1d))
print("Median:",np.median(array_1d))
print("Standard Deviation:",np.std(array_1d))
print("Min:",np.min(array_1d))
print("Max:",np.max(array_1d))
python_list=list(range(1000000))
numpy_array=np.array(python_list)
start=time.time()
result=[x*2 for x in python_list]
print("Python list time:",time.time()-start)
start=time.time()
result=numpy_array*2
print("NumPy array time:",time.time()-start)
print("Random Floats:\n",np.random.rand(3,3))
print("Random Integers:\n",np.random.randint(1,10,(3,3)))
large_array=np.arange(1,1000001)
print("Sum using NumPy:",np.sum(large_array))
print("Shape:",array_2d.shape)
print("Dimensions:",array_2d.ndim)
print("Total Elements:",array_2d.size)